### ISSUE TITLE
Latex 编译出错

### ISSUE THREAD

**Issue by alpaca2333** [kanition/pbrtbook#100]
pbrtbook/structure.tex:22: LaTeX Error: \usepackage before \documentclass.

**Comment by alpaca2333** [comment]
如果可以的话能否在 ReadMe.md 里标注所使用的 latex 版本？
我目前安装的是 texlive 2022.

**Comment by kanition** [comment]
我使用的是texlive 2019，印象中过高版本确实可能造成编译失败，所以后来我降低了版本，但不确定除了2019外还有哪些能编译通过

**Comment by alpaca2333** [comment]
使用 2022 编译成功。感谢~
