### ISSUE TITLE
【我要报错】找不到 ver_info.txt 

### ISSUE THREAD

**Issue by hands133** [kanition/pbrtbook#108]
**报错内容**
编译 main.tex 时出现找不到 ver_info.txt 的错误。

**编译器信息**
1.  XeTeX, Version 3.141592653-2.6-0.999994 (MiKTeX 22.8.28) + VSCode 1.72.2 + Latex Workshop v8.29.0
2. 报错位置：content/readme.tex:25
3. 报错内容：找不到文件 `ver_info.txt`。

**报错信息**
```
! LaTeX Error: File `ver_info.txt' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: txt)

Enter file name: 
content/readme.tex:25: Emergency stop.
<read *> 
         
l.25     {\ttfamily\small\input{ver_info.txt}
                                             }^^M
content/readme.tex:25:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on main.log.
```

**Comment by hands133** [comment]
话说讨论区在哪里

**Comment by kanition** [comment]
编译步骤请参考[编译指南](https://github.com/kanition/pbrtbook/blob/main/CONTRIBUTING.md)
其中文件`ver_info.txt`由编译脚本调用Git获取当前仓库分支名称和SHA-1值后生成，不包含在仓库中，它是用于区分版本的。如果你使用以上编译方法实在无法成功，可以自行新建一个同名空文件，其内容并不影响正文。

讨论区在[这里](https://github.com/kanition/pbrtbook/discussions)
<img width="794" alt="image" src="https://user-images.githubusercontent.com/68691995/197322121-7091ba03-cc0c-49e1-9446-4477817b3757.png">

**Comment by hands133** [comment]
已解决，非常感谢
