### ISSUE TITLE
我想我们可能无法在这个问题上取得一致了。请各自保留观点吧。

### ISSUE THREAD

**Issue by xwc2021** [kanition/pbrtbook#132]
我想我们可能无法在这个问题上取得一致了。请各自保留观点吧。

_Originally posted by @kanition in https://github.com/kanition/pbrtbook/discussions/66#discussioncomment-2505244_

板主大大你好，我好像想通為什麼可以交換微分順序了
之前真的辛苦你了 🙏

**Comment by xwc2021** [comment]
哈哈不會啦
我也看得很慢 🙂

對了
這是我參考這篇後
https://zhuanlan.zhihu.com/p/36896863
發現可以用分果醬來思考I和L
給你參考參考 

E、I、L
E是土司上的果醬厚度
I是單位球上的果醬厚度
L是半球上的果醬厚度

Φ可以想成1瓶果醬 Jam 🍯
這樣
L = Φ / A  / π (這是Philip Dutré教的方法)
L = Φ / 4π / A (這是Unity面光源nit的計算方式)
就差在塗果醬的順序，還有工法

順序
L = d(dΦ / dA) / dω
先平塗到土司上，取出dA上的果醬dΦ
再把dΦ平塗到單位圓(工法)上
再從單位圓塗到(投影)到單位半球上
但多了cos項很不方便
所以投影到單位半球上後，再/cos 假裝是一樣厚
(這是Philip Dutré教的方法)

L = d(dΦ / dω) / dA
先平塗到單位球(工法)上，
再把單位球上的果醬分成 (A/dA)份
所以I和L只差在強弱

![L03](https://user-images.githubusercontent.com/11153808/231732698-669270f3-8f89-4a19-b80f-22f2c61434c0.JPG)

**Comment by xwc2021** [comment]
> 抱歉我还是没看懂你的比喻，没法置评。对我来说直接理解5.9.1节的定义要容易得多，因为我比较习惯直接看简洁的公式。不过很高兴你说自己看明白了！

好的好的 大家各有所好 🙂

不過請容我說一下我需要比喻成果醬厚度的原因
因為常看書上說
L就是1單位面積，1單位立體角，有多少瓦特的能量
可以想成一條射線的方向有多少能量
但
既然是射線大的立體角
為什麼又叫1單位立體角？

明明是從dA大小的區域輻射成L
為什麼又要叫1單位面積？

當我發現用果醬厚度 
L就和立體角取多大,E就和面積取多大脫鉤
才解決我的困擾 😌

**Comment by kanition** [comment]
如果是“1单位”的概念让你困惑，我猜测这样的问题可能还会再次困扰你，因为经典物理学中这样的微分关系实在太多了——速度、加速度、密度、压强、功率……这些都是用这样的微分关系给出的——单位时间的路程、单位时间的速度、单位体积的质量、单位面积的力、单位时间的功，甚至加速度还是路程对时间微分两次的量！果酱厚度的比喻这次能让你想通亮度的定义，但下次可能就帮不上忙了，那时你可能又要苦于构思新的比喻。我还是建议查阅一些高等数学/微积分教材，充分理解“微分”、“导数”以及“无穷小”的定义，你的疑惑会得到解决的。

**Comment by xwc2021** [comment]
真的 我後來也發現 L = dE / dw 已經不是在分果醬了 所以實在很難用別的東西類比 dE = L dw 到底是什麼？
謝謝你 我再去學習 ☺️

**Comment by xwc2021** [comment]
> 如果是“1单位”的概念让你困惑，我猜测这样的问题可能还会再次困扰你，因为经典物理学中这样的微分关系实在太多了——速度、加速度、密度、压强、功率……这些都是用这样的微分关系给出的——单位时间的路程、单位时间的速度、单位体积的质量、单位面积的力、单位时间的功，甚至加速度还是路程对时间微分两次的量！果酱厚度的比喻这次能让你想通亮度的定义，但下次可能就帮不上忙了，那时你可能又要苦于构思新的比喻。我还是建议查阅一些高等数学/微积分教材，充分理解“微分”、“导数”以及“无穷小”的定义，你的疑惑会得到解决的。

太謝謝你了！
現在我明白了，L = dE / dw 的L是ratio，而 dE = L dw 的dE是quantity
我說的厚度就是ratio

然後L的確是在塗果醬
只不過塗法是，先分到土司上A
再取 E * 1 的 quantity，塗到單位圓上
得到 ratio L = E / π

L是ratio ，但 L *1 是 quantity

對A上每個dA都有L，乍看之下，能量沒守恆

但在面光源對shading point dA計算打光時，會執行歸一化 (1 / n) 
Lo = BRDF * Lc * 幾何項 * A * (1 / n) 
![測量L_02](https://user-images.githubusercontent.com/11153808/232178381-0b3a0f93-9a01-4a7d-b9b1-333566442dce.png)

**Comment by xwc2021** [comment]
> 

<html>
<body>
<h1 data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; text-align: left;">E</h1><h3 data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;">E = dΦ / dA = Φ / A</h3><h3 data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: center;"><div class="separator" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="clear: both; orphans: 2; text-align: left; text-decoration-color: initial; text-decoration-style: initial; text-decoration-thickness: initial; text-indent: 0px; widows: 2;"><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: left;"><div data-original-attrs="{&quot;style&quot;:&quot;-webkit-text-stroke-width: 0px;&quot;}" style="color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: 400; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px;">如果果醬是Φ，面積是土司</div><div data-original-attrs="{&quot;style&quot;:&quot;-webkit-text-stroke-width: 0px;&quot;}" style="color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: 400; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px;">E可以想成果醬在土司上的厚度</div><div data-original-attrs="{&quot;style&quot;:&quot;-webkit-text-stroke-width: 0px;&quot;}" style="color: black; font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-caps: normal; font-variant-ligatures: normal; font-weight: 400; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px;"><br></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: center;">

 
--
厚度 ratio微小量 quantity

<br></div></div></div></h3><h1 data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;">dE是什麼</h1><h2 data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; text-align: left;">E的量綱是 ( w / <font data-keep-original-tag="false">m<sup>2 </sup></font>)</h2><h3 data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: center;"><div class="separator" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="clear: both; orphans: 2; text-align: left; text-decoration-color: initial; text-decoration-style: initial; text-decoration-thickness: initial; text-indent: 0px; widows: 2;"><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: left;"><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: left;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;">是1平方公尺有多少 Φ</font></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: left;"><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-weight: 400; text-align: left;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="3">如上圖</font></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-weight: 400; text-align: left;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="3"><br></font></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-weight: 400; text-align: left;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="3">dE是微分E</font></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-weight: 400; text-align: left;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="3">把E分成很多小塊</font></div></div></div></div></h3><h2 data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;">dE的量綱仍是 ( w / <font data-keep-original-tag="false">m<sup>2 </sup></font>)</h2><h3 data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: center;"><div class="separator" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="clear: both; orphans: 2; text-align: left; text-decoration-color: initial; text-decoration-style: initial; text-decoration-thickness: initial; text-indent: 0px; widows: 2;"><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: left;"><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: left;"><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-weight: 400; text-align: left;"></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;"><br></div></div></div></div></h3><h1 data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;">L</h1><h3 data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: center;"><div class="separator" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="clear: both; orphans: 2; text-align: left; text-decoration-color: initial; text-decoration-style: initial; text-decoration-thickness: initial; text-indent: 0px; widows: 2;"><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="text-align: left;"><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: 18.72px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;"></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;">L = dE / dω</div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;">L = E / π</div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;"><br></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;">dE = L dω</div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;">dω = dA / R<sup>2</sup></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;">dE = L dA / R<sup>2</sup></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;"><br></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;">當 R = 1</div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;">dE = L dA</div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;">dE = E dA = dΦ</div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;"><br></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;">所以dE其實是dΦ？</div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: medium; font-weight: 400;">但別忘了dE量綱是 <font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: 18.72px;">(</font><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: 18.72px;">W / </font><font data-keep-original-tag="false">m<sup>2</sup></font><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="font-size: 18.72px;">)</font></div></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: 18.72px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;">要用</font><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;">1平方公尺來測量有多少Φ</font></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: 18.72px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: 18.72px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;">因此，</font><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;">dE相對E來說</font></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: 18.72px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;">能量水平會下降</font><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;">(厚度下降)</font></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: 18.72px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;"><br></font></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: 18.72px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;">把果醬想成水，dA裡的水，被放到</font><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;">1平方公尺的遊泳池</font></div><div data-original-attrs="{&quot;style&quot;:&quot;&quot;}" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: 18.72px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><font data-keep-original-tag="false" data-original-attrs="{&quot;style&quot;:&quot;&quot;}" size="4" style="font-weight: 400;">水位就會下降</font></div><br class="Apple-interchange-newline">
</body>
</html>


> 如果是“1单位”的概念让你困惑，我猜测这样的问题可能还会再次困扰你，因为经典物理学中这样的微分关系实在太多了——速度、加速度、密度、压强、功率……这些都是用这样的微分关系给出的——单位时间的路程、单位时间的速度、单位体积的质量、单位面积的力、单位时间的功，甚至加速度还是路程对时间微分两次的量！果酱厚度的比喻这次能让你想通亮度的定义，但下次可能就帮不上忙了，那时你可能又要苦于构思新的比喻。我还是建议查阅一些高等数学/微积分教材，充分理解“微分”、“导数”以及“无穷小”的定义，你的疑惑会得到解决的。

太謝謝你了！現在我想明白了 🙏

E的量綱是 ( w / m2 )
dE是微分E
把E分成很多小塊
dE的量綱仍然是 ( w / m2 )

**Comment by xwc2021** [comment]
> 如果是“1单位”的概念让你困惑，我猜测这样的问题可能还会再次困扰你，因为经典物理学中这样的微分关系实在太多了——速度、加速度、密度、压强、功率……这些都是用这样的微分关系给出的——单位时间的路程、单位时间的速度、单位体积的质量、单位面积的力、单位时间的功，甚至加速度还是路程对时间微分两次的量！果酱厚度的比喻这次能让你想通亮度的定义，但下次可能就帮不上忙了，那时你可能又要苦于构思新的比喻。我还是建议查阅一些高等数学/微积分教材，充分理解“微分”、“导数”以及“无穷小”的定义，你的疑惑会得到解决的。

太謝謝你了！現在我想明白了 🙏

E的量綱是 ( w / m2 )
dE是微分E
把E分成很多小塊
dE的量綱仍然是 ( w / m2 )
