### ISSUE TITLE
【我要报错】

### ISSUE THREAD

**Issue by Theigrams** [kanition/pbrtbook#133]
**报错内容**
将「Web」错误翻译成了「网页」，此处的Web是 Donald E. Knuth 创建的计算机编程系统，而并非万维网的意思。

**必须提供的信息**
1. 版本号 branch: main commit: 295e4de2b19b34cb9fb3e0290c00d6039d15ca3a
2. 报错位置，第3页的「拓展阅读」部分
<img width="642" alt="image" src="https://user-images.githubusercontent.com/26341831/235668144-7bf17548-5678-458b-ba7b-5cb0ef0f9994.png">

**可选信息**
1. 原书英语原文
<img width="808" alt="image" src="https://user-images.githubusercontent.com/26341831/235668102-bca0ed4b-b5f3-4e61-86c2-3a70436aff42.png">
2. 有关参考文献 

https://en.wikipedia.org/wiki/Web_(programming_system)

**Comment by kanition** [comment]
非常感谢您指出此处错误，在下次更新中我会修正这个错误的！
