### ISSUE TITLE
【我要报错】Over the course of a month or so of feverish hacking

### ISSUE THREAD

**Issue by leemeans** [kanition/pbrtbook#142]
**报错内容**
简单概括要报错的内容。

**必须提供的信息**
1. 版本号 branch:
 main quad commit:
 17eac8ef7b3c4d4824080273e6c57dddd97336f
2. 报错位置，在线版序言
第5页或第6段第3行
3. 报错内容，Over the course of a month or so of feverish hacking翻译成"遭受一个月的黑客攻击后"是不对的，因为这里的"feverish hacking"指的应该是作者心血来潮,狂热的黑客行为，所以翻译为"在一个月的狂热黑客行为/行动之后"更好。

**Comment by kanition** [comment]
非常感谢指正！我将在后续版本中修正该问题
