### ISSUE TITLE
【我要报错】BSDF写成BSFD了

### ISSUE THREAD

**Issue by DeJhon-Huang** [kanition/pbrtbook#147]
**报错内容**
简单概括要报错的内容。
![image](https://github.com/kanition/pbrtbook/assets/18584942/f4b1dd15-ac31-4a66-8cf6-45629e0887f4)

**必须提供的信息**
1. 版本号 v0.7.2
2. 报错位置，例如第367页
3. 报错内容，见图

**Comment by kanition** [comment]
感谢指正！该问题将在后续修正
