### ISSUE TITLE
【我要报错】

### ISSUE THREAD

**Issue by CellarCordial** [kanition/pbrtbook#177]
**报错内容**
符号错误

**必须提供的信息**
1. 版本号：
branch: main
commit: https://github.com/kanition/pbrtbook/commit/17eac8ef7b3c4d4824080273e6c57dddd97336f7

2. 报错位置，109页，2.8.3法线小节，第三段

3. 报错内容：“因为构造的法向量v和曲面上任意切向量t是垂直的”，这里看原文 v 应该是 n 

**可选信息**
1. 原书英语原文
Although tangent vectors transform in the straightforward way, normals require special treatment. Because the normal vector **n** and any tangent vector **t** on the surface are orthogonal by construction

**Comment by kanition** [comment]
感谢如此细心指正！此处确实存在错误，我将于下一次更新中修复该错误
