### ISSUE TITLE
【我要报错】”由“字应为”有“

### ISSUE THREAD

**Issue by LeonHaoWI** [kanition/pbrtbook#187]
**报错内容**
简单概括要报错的内容。

**必须提供的信息**
1. 版本号 branch: main commit: 17eac8ef7b3c4d4824080273e6c57dddd97336f7
2. 报错位置，第335页，第5节第2段第2行
3. 报错内容，”这些辐射量每一个都由它们的光谱功率分布“一句中”由“字应为”有“

**Comment by kanition** [comment]
谢谢你的细心指正！我复查了原文和译文，发现问题根源也许不是“由”字打错了，而是这个长难句不好断句，需要重新调整结构，表达出原文“这些分量由SPD描述，而SPD是波长的分布函数，该分布函数又描述每个波长下的光量”三层意思。我会调整该句的表达，使之更加通畅。
