### ISSUE TITLE
【我要报错】

### ISSUE THREAD

**Issue by ZhongLingXiao** [kanition/pbrtbook#23]
**报错内容**
第二章 
《**2.1 坐标系统**》中`Frame`的翻译从`【坐标系】`==>`【参考系】`

**必须提供的信息**
1. 版本号：master
2. 报错位置：chap0201.tex 第8，9行的【坐标系】三个字。【**注意：后面还有Frame的翻译，也要换掉**】
3. 报错内容：`Frame`翻译成`坐标系`是不对的，因为容易与`坐标系统`混淆，所以翻译为`参考系`更好。

**可选信息**
有关参考文献：
https://zhuanlan.zhihu.com/p/137577939

**Comment by kanition** [comment]
谢谢您的支持，看到有人反馈感觉很开心很值得！

我是初学者，在翻译时对这个词尤其拿不准，确实如您所说，文中“frame”和“coordinate system”一直是混用的，我也不太理解里面有什么细微的区别，暂时按照个人理解把“frame”翻译为“坐标系”，把“coordinate system”翻译为“坐标系统”。

直到前几天我再度纠结起这个问题，索性找到了《数学辞海》[1]，在第一卷335页终于找到了答案：
![图片](https://user-images.githubusercontent.com/68691995/121983558-1ab0a380-cdc4-11eb-8c96-f9a4cf75a3d2.png)
![图片](https://user-images.githubusercontent.com/68691995/121983669-43389d80-cdc4-11eb-8a86-c6e13a89c496.png)

所以“frame”和“coordinate system”原来是同义词，“标架”、“坐标系”、“坐标系统”都是一个意思。

恰巧我在您提出该issue那天作了修改，但当时还没看到这条issue，就把“coordinate system”第一次出现的地方改为“坐标系”（原来是“坐标系统”），把“frame”第一次出现的地方改为“标架”（原来是“坐标系”），旁边批注是“坐标系”的同义词，然后后续所有“坐标系统”都替换为“坐标系”。也就是说，现在只有“坐标系”这一种叫法了。此外那次提交我还改了其他概念的翻译。

您说的“参考系”我觉得对理解书中内容很有帮助，因为这个叫法强调了位置的相对性，这样修改是完全可以的，如果有“reference”一词对应就更好了。只是我已经全都改成“坐标系”了，还混着其他概念的修改，分不清哪些对应“frame”了（哭），一共百余处，所以只好作罢。所幸两种翻译都很合适，个人感觉和“向量”与“矢量”、“内积”与“叉积”类似不会引起误解。

说句题外话，文中ray的翻译才是最让我头疼的，到底什么时候指射线，什么时候指光线，我个人很难分清，不知您怎么看待。

最后，再次感谢您的反馈！

[1]何思谦总, 何思谦, 胡作玄,等. 数学辞海[M]. 东南大学出版社, 2002.

**Comment by ZhongLingXiao** [comment]
谢谢解释。

顺便说一下：您的补充内容超级棒(四元数等部分)，很好的总结了内容，非常感谢。

我对于**ray**的理解：
- 在计算相交过程的时候会把它理解成**射线**；
- 在材质部分的时候会理解成入射/出射**光线** 。

感觉这样会稍微清晰一点。

**Comment by kanition** [comment]
好的，我会认真考虑这个建议的。欢迎对后续内容提出更多建议！

**Comment by kanition** [comment]
好的，我会认真考虑这个建议的。欢迎对后续内容提出更多建议！
