### ISSUE TITLE
想问下这个和清华大学出版社的《物理渲染 从理论到实现》是什么关系

### ISSUE THREAD

**Issue by yhm138** [kanition/pbrtbook#55]
想问下这个和清华大学出版社的《物理渲染 从理论到实现》是什么关系

**Comment by misakalzy** [comment]
那个是第二版，这是第三版，第三版出了之后没人翻译，@kanition来搞了个个人翻译计划。

**Comment by kanition** [comment]
谢谢楼上的解释。简单说就是没有什么关系。
要提醒的是，我是初学者，虽然尽力保证翻译质量，但可能仍有疏漏，所以阅读本书需要擦亮眼睛。这也是对读者的考验。
此外，原书作者计划于明年春季发布第四版。本人为了跟上最新进展，到时将立即终止更新第三版，重新翻译第四版，所以这里存在断更风险。如果您十分看重内容的完整性，建议先阅读您提到的第二版或英文原版。

**Comment by kanition** [comment]
谢谢楼上的解释。简单说就是没有什么关系。
要提醒的是，我是初学者，虽然尽力保证翻译质量，但可能仍有疏漏，所以阅读本书需要擦亮眼睛。这也是对读者的考验。
此外，原书作者计划于明年春季发布第四版。本人为了跟上最新进展，到时将立即终止更新第三版，重新翻译第四版，所以这里存在断更风险。如果您十分看重内容的完整性，建议先阅读您提到的第二版或英文原版。
