### ISSUE TITLE
【我要报错】

### ISSUE THREAD

**Issue by star-hengxing** [kanition/pbrtbook#79]
**报错内容**
第一章打字小错误

**必须提供的信息**
1. 版本号：main 82a2c69fee5986cd4d6d1418f091179c066e8884
2. 报错位置：chap0102.tex 301行末尾
3. 报错内容：BSFD应改为BSDF

**Comment by kanition** [comment]
非常感谢你的仔细阅读与建议！稍后我会修复这处错误。欢迎以后继续提出改进意见哦~
